### ISSUE TITLE
CI rework

### ISSUE THREAD

**Issue by Yohe-Am** [metatypedev/metatype#484]
Some tasks that should be considered for any CI rework effort:

- Replace `rust-cache` by something better, possibly `mozilla/sccache`. Something that works well with very large and numerous build artifacts. 
- Replace all [`action-rs`](https://github.com/actions-rs) actions as they've been archived by the authors
- Fix `dev/lock.ts` to avoid dependency churn
- Use ghjk envs for more things.

**Comment by Yohe-Am** [comment]
@zifeo what do you think of  [merge queues](https://github.blog/2023-07-12-github-merge-queue-is-generally-available) or alternatively Bors?

Also, what about only running the full CI when user wants to merge the PR instead of every push?

**Comment by zifeo** [comment]
@Yohe-Am 

sccache: we definitely must try, however I am not 100% sure it will work well because of those caveats, yet let's give it a try. Happy to set up a R2 backend when you have some time to move forward with that one.

merge-queue: we have played a bit with them and we can re-use them (should already be available) now that we have shorter pipeline. Bors could be an alternative but I am not sure to see the advantage with GitHub ones?
